// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9XZ_sLMj5PPP26P2giKJrer1aj7Jew4k',
    appId: '1:157689769818:web:ad3a0181f0827337464d63',
    messagingSenderId: '157689769818',
    projectId: 'quizds-3b5cc',
    authDomain: 'quizds-3b5cc.firebaseapp.com',
    storageBucket: 'quizds-3b5cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB2f1CKfVk0F2HrrFRlTAgiUA2hIZSW08',
    appId: '1:157689769818:android:751907e929b7420c464d63',
    messagingSenderId: '157689769818',
    projectId: 'quizds-3b5cc',
    storageBucket: 'quizds-3b5cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FBJZV1dwhZ9LKTu_JSigNS9IoQMOb6o',
    appId: '1:157689769818:ios:3ed61ba98e38c16b464d63',
    messagingSenderId: '157689769818',
    projectId: 'quizds-3b5cc',
    storageBucket: 'quizds-3b5cc.firebasestorage.app',
    iosBundleId: 'com.example.quizds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3FBJZV1dwhZ9LKTu_JSigNS9IoQMOb6o',
    appId: '1:157689769818:ios:3ed61ba98e38c16b464d63',
    messagingSenderId: '157689769818',
    projectId: 'quizds-3b5cc',
    storageBucket: 'quizds-3b5cc.firebasestorage.app',
    iosBundleId: 'com.example.quizds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9XZ_sLMj5PPP26P2giKJrer1aj7Jew4k',
    appId: '1:157689769818:web:4b57af2fe7789c1f464d63',
    messagingSenderId: '157689769818',
    projectId: 'quizds-3b5cc',
    authDomain: 'quizds-3b5cc.firebaseapp.com',
    storageBucket: 'quizds-3b5cc.firebasestorage.app',
  );

}